name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.1.0
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: '>=2.13.3 <3.0.0'
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  analyzer: ^2.1.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  meta: ^1.7.0
  rxdart: ^0.27.3
  uuid: ^3.0.5
  webview_flutter: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  test: ^1.19.5

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
